# Generated by Django 5.2.18 on 2026-10-06 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_id',
            field=models.CharField(blank=True, help_text='ID de transaction Wave ou autre API', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'En attente'), ('Paid', 'Payé'), ('Failed', 'Échoué')], default='Pending', max_length=20),
        ),
    ]
